// <auto-generated />
namespace DC.Sofi.Dao.MigrationsSeguridad
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inital : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inital));
        
        string IMigrationMetadata.Id
        {
            get { return "202002221458284_Inital"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
